redirect when login is responded
aluinpoli/vue-auth-training-app pull request #1
Opened 2019-04-05 13:30 UTC by aluinpoli

2019-04-05 13:32 UTC, dobromir-hristov requested changes

2019-04-05 13:32 UTC, dobromir-hristov commented on src/views/Login.vue
> +          this.$router.push(this.$route.query.redirect || '/')
Използвай името на пътя, не самият път.

2019-04-05 13:32 UTC, dobromir-hristov commented on src/router/route-definitions.js
> +      auth: true,
Защо си сложила `auth:true` ?

2019-04-06 21:10 UTC, aluinpoli commented on src/router/route-definitions.js
> +      auth: true,
махнах го.. в началото нещо си играх

2019-04-06 21:10 UTC, aluinpoli commented on src/views/Login.vue
> +          this.$router.push(this.$route.query.redirect || '/')
done

2019-04-07 19:48 UTC, dobromir-hristov approved these changes

2019-04-16 12:49 UTC, merged